# Image J Sorting

### Set our user-controllable variables

**Important:** Your xlsx dataset will need to be properly formatted.  Titles must be Region,	Channel,	ROI,	Area,	Mean, Min,	Max, (in this order) and files must be .xlsx for this.  
`source` should point to an xlsx with a single cell sample dataset.  _-quick note, the `r` before 'string' means that we treat it as a string-literal -- raw and unmodified_  
`subject` should be the sheet name / sample subject in the source file
`threshold` defines the threshold we use to identify the column we wish to mark  
`cell_color` defines the highlight color in the resulting document

In [1]:
try:
    source
except:
    source = r'L2 NM raw data.xlsx'
try:
    threshold
except:
    threshold = 100
try:
    cell_color
except:
    cell_color = r'#009933'
try:
    showoutput
except:
    showoutput = True
try:
    subject
except:
    subject = r'F74'
try:
    showcharts
except:
    showcharts = True

In [2]:
import sys
import sys
if showoutput:
    !{sys.executable} -m pip install numpy pandas tabulate openpyxl xlsxwriter xlrd nbformat Jinja2 plotly
else:
    !{sys.executable} -m pip install numpy pandas tabulate openpyxl xlsxwriter xlrd nbformat Jinja2 plotly > /dev/null

Requirement already satisfied: numpy in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (1.21.2)
Requirement already satisfied: pandas in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (1.3.5)
Requirement already satisfied: tabulate in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (0.8.9)
Requirement already satisfied: openpyxl in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (3.0.9)
Requirement already satisfied: xlsxwriter in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (3.0.2)
Requirement already satisfied: xlrd in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (2.0.1)
Requirement already satisfied: nbformat in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (5.1.3)
Requirement already satisfied: Jinja2 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (3.0.2)
Requirement already satisfied: plotly in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (5.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: et-xmlfile in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: traitlets>=4.1 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from nbformat) (5.1.1)
Requirement already satisfied: jupyter-core in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from nbformat) (4.9.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from nbformat) (3.2.0)
Requirement already satisfied: ipython-genutils in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from nbformat) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from Jinja2) (2.0.1)
Requirement already satisfied: tenacity>=6.2.0 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from plotly) (8.0.1)
Requirement already satisfied: six in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from plotly) (1.15.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat) (21.4.0)
Requirement already satisfied: setuptools in /Users/julia/opt/anaconda3/envs/DonaldsonCode/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat) (58.0.4)

Next, we `import` the libraries we want to use with import statements.  This effectively makes anything in their namespaces available in our application.  In this case, we'll use the optional `as` statement to alias the pandas & numpy libraries, and `from` to import the tabulate & display module inside their respective packages.

In [3]:
import pandas as pd
import numpy as np
from IPython.display import display
from tabulate import tabulate

We use the Pandas library, which we've aliased to the `pd` namespace, to load the file contained in the variable `source`

Pandas is a handy utility for manipulating excel-style data.  We set the `Region` & `Channel` index here for the initial grouping

In [4]:
data = pd.read_excel(source, sheet_name=subject).set_index(['Region','Channel'])

#### Let's take a quick look at our data...
We've reformatted our data to be a little simpler to use with Pandas.  We could load the existing data as-is with some slight modifications, and duplicate keys will show up as `key key.1 key.2 ...`, etc  
This would require us to melt the table, pivot, & group - I think a better approach if possible is to restructure the data slightly as seen in the "Mockup" sheet.  I can help you write a data converter for all of your existing samples if you'd like, but the code will be a little difficult to follow.  

So, for now you can see we've added Sample & Core columns and dropped it into a uniform array we can easily use in Pandas

In [5]:
if showoutput:
    display(data)
    print(len(data))

                      ROI     Area     Mean  Min   Max
Region       Channel
RIGHT CORE 1 D1DR       1  122.437  199.631   66   635
             D1DR       2  141.749  421.627   75  1255
             D1DR       3   61.798   93.344   68   149
             D1DR       4  114.713   80.869   64   109
             D1DR       5   80.724   81.397   65   103
...                   ...      ...      ...  ...   ...
LEFT SHELL 3 OXTR     109   69.137    0.486    0    46
             OXTR     110   66.433    0.907    0    56
             OXTR     111   69.523    0.511    0    41
             OXTR     112   65.274    0.645    0    31
             OXTR     113   79.565    1.306    0    43

[4293 rows x 5 columns]

4293

We have our data.  Now, this sorts our data to more eaisily identify the first core.max Δ > threshold using indexes & regroup it.

In [6]:
sorted_data = data.sort_values(by=['Region','Channel','Max'])
if showoutput:
    display(sorted_data)

                       ROI     Area     Mean  Min   Max
Region        Channel
LEFT CORE 1   D1DR      98   95.015   69.423   56    95
              D1DR      34   67.592   75.486   58   103
              D1DR      39   68.364   71.028   55   104
              D1DR     106   76.089   78.650   61   104
              D1DR      24   70.682   77.459   60   105
...                    ...      ...      ...  ...   ...
RIGHT SHELL 3 OXTR      70  180.759   17.120    0  2236
              OXTR      98  123.596   25.572    0  2351
              OXTR      76  123.210   53.978    0  2533
              OXTR      67  136.342  300.363    0  3179
              OXTR      20  191.574  177.688    0  4095

[4293 rows x 5 columns]

Table is now sorted by Max, now we can group the regions & channels for our Max Δ calculation

In [7]:
sorted_data['Max_Delta'] = sorted_data.groupby(['Region','Channel'])['Max'].diff()
if showoutput:
    display(sorted_data)

                       ROI     Area     Mean  Min   Max  Max_Delta
Region        Channel
LEFT CORE 1   D1DR      98   95.015   69.423   56    95        NaN
              D1DR      34   67.592   75.486   58   103        8.0
              D1DR      39   68.364   71.028   55   104        1.0
              D1DR     106   76.089   78.650   61   104        0.0
              D1DR      24   70.682   77.459   60   105        1.0
...                    ...      ...      ...  ...   ...        ...
RIGHT SHELL 3 OXTR      70  180.759   17.120    0  2236       44.0
              OXTR      98  123.596   25.572    0  2351      115.0
              OXTR      76  123.210   53.978    0  2533      182.0
              OXTR      67  136.342  300.363    0  3179      646.0
              OXTR      20  191.574  177.688    0  4095      916.0

[4293 rows x 6 columns]

Done! Now we just need to highlight our target data and write it out to an xlsx

Now we generate a threshold table, using our calculated Max_Delta column.  We group on our indexes, and invoke first() on each group.  
 
Additionally, we add the column `Max_Delta_First_Hit` to the `first_threshold_table` dataframe that we'll need later on.

In [8]:
first_threshold_table = sorted_data.query('Max_Delta >= 100').groupby(['Region','Channel']).first()
first_threshold_table['Max_Delta_First_Hit'] = True
if showoutput:
    display(first_threshold_table)

                       ROI     Area      Mean  Min   Max  Max_Delta  \
Region        Channel
LEFT CORE 1   D2DR       6   64.888   300.208   48  1224      104.0
              OXTR      95   67.978     3.108    0   453      111.0
LEFT CORE 2   D1DR      20  212.045   459.882  115  1425      100.0
              D2DR      24  191.960   296.318   26  1657      197.0
              OXTR      82  162.220     5.536    0   515      136.0
LEFT SHELL 1  D1DR      98  146.384  1065.187  162  2493      539.0
              D2DR      53   62.184   766.814  154  1761      107.0
              OXTR     110  145.612     9.568    0   513      113.0
LEFT SHELL 2  D1DR      49  114.326   603.615  216  1763      197.0
              D2DR     101   94.242    45.971   27   225      161.0
              OXTR     111  141.363     8.396    0   575      349.0
LEFT SHELL 3  D2DR      49  108.533    33.765   23   194      131.0
              OXTR      85  186.167     9.774    0   579      349.0
RIGHT CORE 1  D2DR      56  152.950    78.753   31  1223      102.0
              OXTR      48  100.036     2.996    0   219      105.0
RIGHT CORE 2  D1DR      43   84.972   988.291  185  2162      118.0
              D2DR      74   83.814   207.691   40  1576      119.0
              OXTR     153  184.622     4.130    0   517      318.0
RIGHT SHELL 1 D1DR      74  105.829   983.022  265  2128      114.0
              D2DR     119  210.886   116.877   26  1800      115.0
              OXTR     168  177.283     4.148    0   549      127.0
RIGHT SHELL 2 D1DR      26  112.009   929.493  436  2135      135.0
              D2DR     102   71.454   594.584  198  1686      110.0
              OXTR      78  130.935     2.628    0   458      201.0
RIGHT SHELL 3 D2DR      90   83.427   627.648  120  1818      144.0
              OXTR      55  190.415     7.590    0   416      203.0

                       Max_Delta_First_Hit
Region        Channel
LEFT CORE 1   D2DR                    True
              OXTR                    True
LEFT CORE 2   D1DR                    True
              D2DR                    True
              OXTR                    True
LEFT SHELL 1  D1DR                    True
              D2DR                    True
              OXTR                    True
LEFT SHELL 2  D1DR                    True
              D2DR                    True
              OXTR                    True
LEFT SHELL 3  D2DR                    True
              OXTR                    True
RIGHT CORE 1  D2DR                    True
              OXTR                    True
RIGHT CORE 2  D1DR                    True
              D2DR                    True
              OXTR                    True
RIGHT SHELL 1 D1DR                    True
              D2DR                    True
              OXTR                    True
RIGHT SHELL 2 D1DR                    True
              D2DR                    True
              OXTR                    True
RIGHT SHELL 3 D2DR                    True
              OXTR                    True

Next we need to merge the `first_threshold_table` dataframe with our `sorted_data` dataframe.  Calling .merge() will drop the indexes, so we first invoke reset_index() first  
Our merge strategy in this scenario will be `left` - I'd recommend reading up on SQL & structured data `JOIN` operations to understand the methodology

In [9]:
merged_data = sorted_data.reset_index().merge(first_threshold_table, how='left')
if showoutput:
    display(merged_data)

,Region,Channel,ROI,Area,Mean,Min,Max,Max_Delta,Max_Delta_First_Hit
0,LEFT CORE 1,D1DR,98,95.015,69.423,56,95,NaN,NaN
1,LEFT CORE 1,D1DR,34,67.592,75.486,58,103,8.0,NaN
2,LEFT CORE 1,D1DR,39,68.364,71.028,55,104,1.0,NaN
3,LEFT CORE 1,D1DR,106,76.089,78.650,61,104,0.0,NaN
4,LEFT CORE 1,D1DR,24,70.682,77.459,60,105,1.0,NaN
...,...,...,...,...,...,...,...,...,...
4288,RIGHT SHELL 3,OXTR,70,180.759,17.120,0,2236,44.0,NaN
4289,RIGHT SHELL 3,OXTR,98,123.596,25.572,0,2351,115.0,NaN
4290,RIGHT SHELL 3,OXTR,76,123.210,53.978,0,2533,182.0,NaN
4291,RIGHT SHELL 3,OXTR,67,136.342,300.363,0,3179,646.0,NaN
4292,RIGHT SHELL 3,OXTR,20,191.574,177.688,0,4095,916.0,NaN

This defines a styler function to color our cells.

In [10]:
def style_when_true(series):
    match_table = [1 if x == True else 0 for x in series]
    return [f'background-color: {cell_color}' if v else '' for v in match_table]

Next, we want to apply our formatter to highlight the cell using `Max_Delta_First_Hit`

In [11]:
formatted_data = merged_data.style.apply(style_when_true, subset='Max_Delta_First_Hit')
if showoutput:
        display(merged_data.head(25).style.apply(style_when_true, subset='Max_Delta_First_Hit'))

## Part 2 - more detailed data analysis / output.

In [12]:
#Define a new channel-based dataframe
df_channel = pd.DataFrame(columns=[
    'Region',
    'Channel',
    'Positive',
    'Negative',
    'Count',
    'Positive_Ratio',
])

#Define a new region-based dataframe
df_region = pd.DataFrame(columns=[
    'Region',
    'Count',
    'C1_Positive',
    'C1_Positive_Ratio',
    'C2_Positive',
    'C2_Positive_Ratio',
    'C3_Positive',
    'C3_Positive_Ratio',
    'C1C2_Positive',
    'C1C2_Positive_Ratio',
    'C1C3_Positive',
    'C1C3_Positive_Ratio',
    'C2C3_Positive',
    'C2C3_Positive_Ratio',
    'C1C2C3_Positive',
    'C1C2C3_Positive_Ratio',
    'C1-Only_Positive',
    'C1-Only_Positive_Ratio',
    'C2-Only_Positive',
    'C2-Only_Positive_Ratio',
    'C3-Only_Positive',
    'C3-Only_Positive_Ratio',
    'C1C2-Only_Positive',
    'C1C2-Only_Positive_Ratio',
    'C1C3-Only_Positive',
    'C1C3-Only_Positive_Ratio',
    'C2C3-Only_Positive',
    'C2C3-Only_Positive_Ratio',
    'Negative',
    'Negative_Ratio',
])

#Calculate our channel data, where a positive result is derived from Max > 0
for i in merged_data.groupby(['Region','Channel']):
    df_channel = df_channel.append({
        'Region':i[0][0],
        'Channel':i[0][1],
        'Positive':sum(i[1]['Max'] > 0),
        'Negative':sum(i[1]['Max'] <= 0),
        'Count':len(i[1]),
        'Positive_Ratio':sum(i[1]['Max'] > 0) / len(i[1]['Max'])
        }, ignore_index=True)

#Set indexer on channel dataframe
df_channel = df_channel.set_index('Region')

#Fill region dataframe with regions & zero out all values
df_region.Region  = merged_data.Region.unique()
df_region = df_region.set_index('Region')
for col in df_region.columns:
    df_region[col].values[:] = 0

#Calculate our region data, where a positive result is derived from Max > 0 with 'AND' channel groupings
for i in merged_data.groupby(['Region','ROI']):
    try:
        df_region.at[i[1].iloc[0]['Region'], 'Count'] += 1
        df_region.at[i[1].iloc[0]['Region'], 'C1_Positive'] += i[1].iloc[0]['Max'] > 0
        df_region.at[i[1].iloc[1]['Region'], 'C2_Positive'] += i[1].iloc[1]['Max'] > 0
        df_region.at[i[1].iloc[2]['Region'], 'C3_Positive'] += i[1].iloc[2]['Max'] > 0
        df_region.at[i[1].iloc[2]['Region'], 'C1C2_Positive'] += (i[1].iloc[0]['Max'] > 0) and (i[1].iloc[1]['Max'] > 0)
        df_region.at[i[1].iloc[2]['Region'], 'C1C3_Positive'] += (i[1].iloc[0]['Max'] > 0) and (i[1].iloc[2]['Max'] > 0)
        df_region.at[i[1].iloc[2]['Region'], 'C2C3_Positive'] += (i[1].iloc[1]['Max'] > 0) and (i[1].iloc[2]['Max'] > 0)
        df_region.at[i[1].iloc[0]['Region'], 'C1-Only_Positive'] += i[1].iloc[0]['Max'] > 0 and (i[1].iloc[1]['Max'] <= 0) and (i[1].iloc[2]['Max'] <= 0)
        df_region.at[i[1].iloc[1]['Region'], 'C2-Only_Positive'] += i[1].iloc[1]['Max'] > 0 and (i[1].iloc[0]['Max'] <= 0) and (i[1].iloc[2]['Max'] <= 0)
        df_region.at[i[1].iloc[2]['Region'], 'C3-Only_Positive'] += i[1].iloc[2]['Max'] > 0 and (i[1].iloc[0]['Max'] <= 0) and (i[1].iloc[1]['Max'] <= 0)
        df_region.at[i[1].iloc[2]['Region'], 'C1C2-Only_Positive'] += (i[1].iloc[0]['Max'] > 0) and (i[1].iloc[1]['Max'] > 0) and (i[1].iloc[2]['Max'] <= 0)
        df_region.at[i[1].iloc[2]['Region'], 'C1C3-Only_Positive'] += (i[1].iloc[0]['Max'] > 0) and (i[1].iloc[2]['Max'] > 0) and (i[1].iloc[1]['Max'] <= 0)
        df_region.at[i[1].iloc[2]['Region'], 'C2C3-Only_Positive'] += (i[1].iloc[1]['Max'] > 0) and (i[1].iloc[2]['Max'] > 0) and (i[1].iloc[0]['Max'] <= 0)
        df_region.at[i[1].iloc[2]['Region'], 'C1C2C3_Positive'] += (i[1].iloc[0]['Max'] > 0) and (i[1].iloc[1]['Max'] > 0) and (i[1].iloc[2]['Max'] > 0)
        df_region.at[i[1].iloc[2]['Region'], 'Negative'] += (i[1].iloc[0]['Max'] <= 0) and (i[1].iloc[1]['Max'] <= 0) and (i[1].iloc[2]['Max'] <= 0)
    except Exception as e:
        print("Data input issue, we ran into a problem here:")
        print(i)
        raise(e)

#Calculate ratios
df_region['C1_Positive_Ratio'] = (df_region['C1_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C2_Positive_Ratio'] = (df_region['C2_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C3_Positive_Ratio'] = (df_region['C3_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C1C2_Positive_Ratio'] = (df_region['C1C2_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C1C3_Positive_Ratio'] = (df_region['C1C3_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C2C3_Positive_Ratio'] = (df_region['C2C3_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C1-Only_Positive_Ratio'] = (df_region['C1-Only_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C2-Only_Positive_Ratio'] = (df_region['C2-Only_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C3-Only_Positive_Ratio'] = (df_region['C3-Only_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C1C2-Only_Positive_Ratio'] = (df_region['C1C2-Only_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C1C3-Only_Positive_Ratio'] = (df_region['C1C3-Only_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C2C3-Only_Positive_Ratio'] = (df_region['C2C3-Only_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['C1C2C3_Positive_Ratio'] = (df_region['C1C2C3_Positive'] / df_region['Count']).astype(np.double).round(5)
df_region['Negative_Ratio'] = (df_region['Negative'] / df_region['Count']).astype(np.double).round(5)
if showoutput:
    display(df_region)
    display(df_channel.groupby(['Region','Channel']).first())

,Count,C1_Positive,C1_Positive_Ratio,C2_Positive,C2_Positive_Ratio,C3_Positive,C3_Positive_Ratio,C1C2_Positive,C1C2_Positive_Ratio,C1C3_Positive,...,C3-Only_Positive,C3-Only_Positive_Ratio,C1C2-Only_Positive,C1C2-Only_Positive_Ratio,C1C3-Only_Positive,C1C3-Only_Positive_Ratio,C2C3-Only_Positive,C2C3-Only_Positive_Ratio,Negative,Negative_Ratio
Region,,,,,,,,,,,,,,,,,,,,,
LEFT CORE 1,106,106,1.0,106,1.0,106,1.00000,106,1.0,106,...,0,0.0,0,0.00000,0,0.0,0,0.0,0,0.0
LEFT CORE 2,94,94,1.0,94,1.0,94,1.00000,94,1.0,94,...,0,0.0,0,0.00000,0,0.0,0,0.0,0,0.0
LEFT SHELL 1,236,236,1.0,236,1.0,231,0.97881,236,1.0,231,...,0,0.0,5,0.02119,0,0.0,0,0.0,0,0.0
LEFT SHELL 2,111,111,1.0,111,1.0,111,1.00000,111,1.0,111,...,0,0.0,0,0.00000,0,0.0,0,0.0,0,0.0
LEFT SHELL 3,113,113,1.0,113,1.0,113,1.00000,113,1.0,113,...,0,0.0,0,0.00000,0,0.0,0,0.0,0,0.0
RIGHT CORE 1,164,164,1.0,164,1.0,157,0.95732,164,1.0,157,...,0,0.0,7,0.04268,0,0.0,0,0.0,0,0.0
RIGHT CORE 2,165,165,1.0,165,1.0,159,0.96364,165,1.0,159,...,0,0.0,6,0.03636,0,0.0,0,0.0,0,0.0
RIGHT SHELL 1,172,172,1.0,172,1.0,165,0.95930,172,1.0,165,...,0,0.0,7,0.04070,0,0.0,0,0.0,0,0.0
RIGHT SHELL 2,140,140,1.0,140,1.0,140,1.00000,140,1.0,140,...,0,0.0,0,0.00000,0,0.0,0,0.0,0,0.0
RIGHT SHELL 3,130,130,1.0,130,1.0,130,1.00000,130,1.0,130,...,0,0.0,0,0.00000,0,0.0,0,0.0,0,0.0

                       Positive  Negative  Count  Positive_Ratio
Region        Channel
LEFT CORE 1   D1DR          106         0    106        1.000000
              D2DR          106         0    106        1.000000
              OXTR          106         0    106        1.000000
LEFT CORE 2   D1DR           94         0     94        1.000000
              D2DR           94         0     94        1.000000
              OXTR           94         0     94        1.000000
LEFT SHELL 1  D1DR          236         0    236        1.000000
              D2DR          236         0    236        1.000000
              OXTR          231         5    236        0.978814
LEFT SHELL 2  D1DR          111         0    111        1.000000
              D2DR          111         0    111        1.000000
              OXTR          111         0    111        1.000000
LEFT SHELL 3  D1DR          113         0    113        1.000000
              D2DR          113         0    113        1.000000
              OXTR          113         0    113        1.000000
RIGHT CORE 1  D1DR          164         0    164        1.000000
              D2DR          164         0    164        1.000000
              OXTR          157         7    164        0.957317
RIGHT CORE 2  D1DR          165         0    165        1.000000
              D2DR          165         0    165        1.000000
              OXTR          159         6    165        0.963636
RIGHT SHELL 1 D1DR          172         0    172        1.000000
              D2DR          172         0    172        1.000000
              OXTR          165         7    172        0.959302
RIGHT SHELL 2 D1DR          140         0    140        1.000000
              D2DR          140         0    140        1.000000
              OXTR          140         0    140        1.000000
RIGHT SHELL 3 D1DR          130         0    130        1.000000
              D2DR          130         0    130        1.000000
              OXTR          130         0    130        1.000000

Almost done! Now write out dataframes to a new xlsx document.
We currently write out a summary sheet containing the selected cells which exceeded the threshold in the dataset, and the data with highlighted styling.

In [13]:
with pd.ExcelWriter(f"{subject}.xlsx", engine='xlsxwriter') as writer:
    first_threshold_table.to_excel(writer, sheet_name=f'{subject}-summary')
    df_region.to_excel(writer, sheet_name=f'{subject}-regions')
    df_channel.to_excel(writer, sheet_name=f'{subject}-channels')
    formatted_data.to_excel(writer, sheet_name=subject, index=True)
    
    #Set column formats
    workbook = writer.book
    region_worksheet = writer.sheets[f'{subject}-regions']
    pct_format = workbook.add_format({'num_format': '0.00%'})
    region_worksheet.set_column('D:D', None, pct_format)
    region_worksheet.set_column('F:F', None, pct_format)
    region_worksheet.set_column('H:H', None, pct_format)
    region_worksheet.set_column('J:J', None, pct_format)
    region_worksheet.set_column('L:L', None, pct_format)
    region_worksheet.set_column('N:N', None, pct_format)
    region_worksheet.set_column('P:P', None, pct_format)
    region_worksheet.set_column('R:R', None, pct_format)
    region_worksheet.set_column('T:T', None, pct_format)
    region_worksheet.set_column('V:V', None, pct_format)
    region_worksheet.set_column('X:X', None, pct_format)
    region_worksheet.set_column('Z:Z', None, pct_format)
    region_worksheet.set_column('AB:AB', None, pct_format)
    region_worksheet.set_column('AD:AD', None, pct_format)
    
    #Autofit columns
    for sheetname, df in writer.sheets.items():
        worksheet = writer.sheets[sheetname]
        worksheet.set_column(0, 29, 25)
print(f"Successfully wrote {subject}.xlsx")

Successfully wrote F74.xlsx

## We're done, and you should now have a new xlsx file based on the subject name in your folder.
REMEMBER to rename each file as soon as it's downloaded to specify the cohort (paired, naive, species), neuroatatomical level and if it is threshold, channel, or final analyzed data.